version: "3.1"
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: notes_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "6000:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
